### ISSUE TITLE
Caption package missing

### ISSUE THREAD

**Issue by XHotSniperX** [ivangiangreco/basilea-latex#1]
The Basilea file should import the caption package in order to use captions correctly.

\usepackage{caption}

**Comment by ivangiangreco** [comment]
Captions can very well be used in the current version. I do not understand what you mean by "use captions correctly".

**Comment by XHotSniperX** [comment]
Without using the caption package the captions are not centered (look at the pdf here).\centering doesn't work. With the use of the caption package it works fine.

Could you please tell me how to manage that without importing caption?

**Comment by ivangiangreco** [comment]
Sorry, this is not an issue with the template but your personal preference to have the caption centered. Please consult other forums/... regarding this question.
