### ISSUE TITLE
offset in subfigure references

### ISSUE THREAD

**Issue by mpas97** [ivangiangreco/basilea-latex#7]
References to subfigures have an offset of one.

E.g., having tm1, tm2, tm3, tm4 and referenceing to them results in (), (a), (b), (c) instead of (a), (b), (c), (d).

<img width="598" alt="grafik" src="https://user-images.githubusercontent.com/9994218/86096061-14da8900-bab3-11ea-846d-711e068ee0d7.png">

<img width="598" alt="grafik" src="https://user-images.githubusercontent.com/9994218/86095965-f1174300-bab2-11ea-9b7e-800a8e5b5e92.png">

**Comment by ivangiangreco** [comment]
This is strange, as `\ref{fig:tm:tm1}` (or `cref`) produces the correct result with me:

<img width="465" alt="Screenshot 2020-07-01 at 08 26 03" src="https://user-images.githubusercontent.com/462823/86210312-aeb63a80-bb74-11ea-9bd5-4bc5fe06759c.png">

I have adjusted the exemplary text to make it clearer.

**Comment by mpas97** [comment]
@ivangiangreco so what should and can I do? It happened in my thesis file already (on all figures with subfigures, so its not an exception case), and for the example above I've cloned the repo again (to have a clean setup), added the few references and it happens exactly the same.

**Comment by ivangiangreco** [comment]
Have you tried updating your Latex installation and all the packages?

**Comment by mpas97** [comment]
Somethig goes really wrong. Using the newest 1:1 the repo clone without changes (so there is now this cref), references to the whole section instead of the subfigure only.

<img width="598" alt="grafik" src="https://user-images.githubusercontent.com/9994218/86211499-c8588180-bb76-11ea-98e5-d8f9cf96b99c.png">

I will check for Latex / package updates, but I don't think there are some or that they will fix this little something.

**Comment by mpas97** [comment]
There where indeed some Latex and package updates. After having upgraded everything, the problem remains exactly the same though :/

**Comment by mpas97** [comment]
I just searched for subbottom references. As we can see in [the example](
https://tex.stackexchange.com/questions/31823/how-to-reference-subfigure-in-caption/31875#31875) the labels come earlier in the commands. Now \ref and \cref are working fine for me too.
<img width="499" alt="grafik" src="https://user-images.githubusercontent.com/9994218/86219504-96e5b300-bb82-11ea-8a0f-8d5449cdffd8.png">
Can you please check if this works for you too? If yes, we could use that so it works for more people ;)

**Comment by ivangiangreco** [comment]
Oh, yes, that's a very good point. Depending on which Typesetter I use, I get difference results. Your suggestion definitely seems to work. Please find it in commit a40a613. Thanks a lot for the feedback!
